name: Releases

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: echo "VERSI=v1.1" >> $GITHUB_ENV
    - run: echo "hellow world" > a.txt
    - run: ls ${{ GITHUB_WORKSPACE }}
    - run: echo "MITSU=${{ GITHUB_WORKSPACE }}" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1.13.0
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        makeLatest: false
        commit: "main"
        tag: ${{ env.VERSI }}
        name: "YOUU ${{ env.VERSI }}"
        repo: "releases"
        token: ${{ secrets.API_TOKEN_GITHUB }}
        artifacts: "${{ env.MITSU }}/a.txt"
        bodyFile: "README.md"
