name: Releases

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: echo "hellow world" > a.txt
    - run: ls
    - uses: ncipollo/release-action@v1.13.0
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        makeLatest: false
        commit: "main"
        tag: "v1.0"
        name: "hii"
        repo: "releases"
        token: ${{ secrets.API_TOKEN_GITHUB }}
        artifacts: "a.txt"
        bodyFile: "README.md"
